"project_id" : "493925"
"api_token" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    source: '/docs/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%',
  },
]